Added additional methods to Mark-,Pupil-,Clazz-Service. Added necessa…
maximka777/MPP.Java.SchoolJournal pull request #15
Opened 2017-03-13 19:38 UTC by zasamen

…ry specifications. Issued complex criteria

2017-03-14 18:10 UTC, mbarouski requested changes

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/controller/MarkAPIController.java
> +            @RequestParam(value = "startTerm") Date startTerm,
Date -> String

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/controller/MarkAPIController.java
> +                    getMarksForTermOrder(classId, startTerm, endTerm),
I think for simplicity out app will work with one term, so del startTerm and endTerm

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/controller/MarkAPIController.java
> +                    new ErrorObject("Error in class getting"),
msg text is incorrect

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/controller/MarkAPIController.java
> +            @RequestParam(value = "startTerm") Date startTerm,
the same for term dates

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/controller/PupilAPIController.java
>      public ResponseEntity get(HttpServletRequest request)
change this method to getting of list of pupils that has no class

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/controller/PupilAPIController.java
> +    @RequestMapping(value = "/{classId}", method = DELETE)
classId -> pupilId

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/controller/PupilAPIController.java
> +    @RequestMapping(value = "/{classId}", method = GET)
classId -> pupilId

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/controller/PupilAPIController.java
> +            LOGGER.info("Get Pupil entities Controller method");
use more informative messages in `.info()` or not use it

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/repository/specification/mark/MarkSpecificationByPupilIdAndDates.java
> +public class MarkSpecificationByPupilIdAndDates extends MarkSpecification {
delete dates

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/service/IMarkService.java
> +    List<Mark> getMarksForTermOrder(int classId, Date startTerm,Date endTerm) throws ServiceException;
delete dates

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +        validateCreatingMarkDate(mark.getDate());
change name of method to more informative

2017-03-14 18:10 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +        validateCreatingMarkDate(mark.getDate());
we will ignore this date, so we can not check

2017-03-14 18:10 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +        List<Mark> markList;
test it

2017-03-14 18:10 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +    public List<Pupil> getListOfPupils(int clazzId) throws ServiceException {
change name to `getListOfPupilsInClass`

2017-03-14 18:10 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/SubjectInScheduleService.java
> +    private static final long START_WORK_DAY_TIME_MILLIS = 25_200_000;//7h*60m*60s*1000ms
GOOD!

2017-03-14 18:10 UTC, maximka777 commented on server/src/main/java/school/journal/utils/ValidateServiceUtils.java
> +            (Date startDate, Date endDate) throws ValidationException{
move to the new string only throwing

2017-03-14 18:20 UTC, maximka777 commented
and use some StringFormatter for sql query building

2017-03-16 15:23 UTC, zasamen commented on server/src/main/java/school/journal/controller/MarkAPIController.java
> +            @RequestParam(value = "startTerm") Date startTerm,
done

2017-03-16 15:24 UTC, zasamen commented on server/src/main/java/school/journal/controller/MarkAPIController.java
> +                    getMarksForTermOrder(classId, startTerm, endTerm),
get mark of full time?

2017-03-16 15:25 UTC, zasamen commented on server/src/main/java/school/journal/controller/MarkAPIController.java
> +                    new ErrorObject("Error in class getting"),
done

2017-03-16 15:26 UTC, zasamen commented on server/src/main/java/school/journal/controller/MarkAPIController.java
> +            @RequestParam(value = "startTerm") Date startTerm,
the same question

2017-03-16 15:28 UTC, zasamen commented on server/src/main/java/school/journal/controller/PupilAPIController.java
>      public ResponseEntity get(HttpServletRequest request)
What do you mean?

2017-03-16 15:29 UTC, zasamen commented on server/src/main/java/school/journal/controller/PupilAPIController.java
> +    @RequestMapping(value = "/{classId}", method = DELETE)
done

2017-03-16 15:30 UTC, zasamen commented on server/src/main/java/school/journal/controller/PupilAPIController.java
> +    @RequestMapping(value = "/{classId}", method = GET)
done

2017-03-16 15:30 UTC, zasamen commented on server/src/main/java/school/journal/controller/PupilAPIController.java
> +            LOGGER.info("Get Pupil entities Controller method");
What should i use?

2017-03-16 15:31 UTC, zasamen commented on server/src/main/java/school/journal/service/IMarkService.java
> +    List<Mark> getMarksForTermOrder(int classId, Date startTerm,Date endTerm) throws ServiceException;
id check it in COontroller

2017-03-16 15:32 UTC, zasamen commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +        validateCreatingMarkDate(mark.getDate());
?

2017-03-16 15:34 UTC, zasamen commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +    public List<Pupil> getListOfPupils(int clazzId) throws ServiceException {
done

2017-03-16 15:35 UTC, zasamen commented on server/src/main/java/school/journal/utils/ValidateServiceUtils.java
> +            (Date startDate, Date endDate) throws ValidationException{
done

2017-03-17 20:22 UTC, zasamen commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +        validateCreatingMarkDate(mark.getDate());
deleted

2017-03-17 20:22 UTC, zasamen commented on server/src/main/java/school/journal/service/IMarkService.java
> +    List<Mark> getMarksForTermOrder(int classId, Date startTerm,Date endTerm) throws ServiceException;
ok

2017-03-17 20:23 UTC, zasamen commented on server/src/main/java/school/journal/controller/PupilAPIController.java
> +            LOGGER.info("Get Pupil entities Controller method");
What information should be in info like that?

2017-03-17 20:23 UTC, zasamen commented on server/src/main/java/school/journal/controller/PupilAPIController.java
>      public ResponseEntity get(HttpServletRequest request)
?

2017-03-17 20:31 UTC, merged