Created CSV service Interface
maximka777/MPP.Java.SchoolJournal pull request #40
Opened 2017-05-04 23:10 UTC by zasamen

2017-05-06 19:34 UTC, zasamen commented
Updated.

2017-05-08 16:45 UTC, mbarouski requested changes

2017-05-08 16:45 UTC, maximka777 commented on server/src/main/java/school/journal/controller/ClassAPIController.java
> +//            generationService.generateMarksDocument(response.getOutputStream(), DocumentType.CSV, 1, 1);
what are comments there?

2017-05-08 16:45 UTC, maximka777 commented on server/src/main/java/school/journal/service/IDocumentGenerationService.java
> +package school.journal.service;
what is it?

2017-05-08 16:45 UTC, maximka777 commented on server/src/main/java/school/journal/service/document/generation/CSVService.java
> +}
SHIT!!!!

2017-05-08 16:45 UTC, maximka777 commented on server/src/main/java/school/journal/service/document/generation/GenerationService.java
> +//        List<Teacher> teacherList = teacherService.getListOfTeachersForClass(classId);
delete

2017-05-08 18:56 UTC, zasamen commented on server/src/main/java/school/journal/controller/ClassAPIController.java
> +//            generationService.generateMarksDocument(response.getOutputStream(), DocumentType.CSV, 1, 1);
It is testing endpoint. If u want to try run my generation way, you shouldn't write it.

I checked correctness of generation csv here.

2017-05-08 18:58 UTC, zasamen commented on server/src/main/java/school/journal/service/document/generation/CSVService.java
> +}
But what do u want?
We shouldn't return output stream.
the best way is null.

2017-05-08 19:04 UTC, zasamen commented on server/src/main/java/school/journal/service/document/generation/GenerationService.java
> +//        List<Teacher> teacherList = teacherService.getListOfTeachersForClass(classId);
ok

2017-05-08 19:04 UTC, zasamen commented on server/src/main/java/school/journal/service/IDocumentGenerationService.java
> +package school.journal.service;
deleted

2017-05-08 19:08 UTC, zasamen commented on server/src/main/java/school/journal/controller/ClassAPIController.java
> +//            generationService.generateMarksDocument(response.getOutputStream(), DocumentType.CSV, 1, 1);
ok.deleting

2017-05-09 08:31 UTC, merged