Retsam. Changed services to common interface
maximka777/MPP.Java.SchoolJournal pull request #9
Opened 2017-03-02 20:43 UTC by zasamen

2017-03-03 03:33 UTC, zasamen commented
so? what is wrong?

2017-03-03 05:46 UTC, mbarouski requested changes

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/IPupilService.java
> +    Pupil movePupulToAnotherClass(Pupil pupil, Clazz clazz) throws ServiceException;
`movePupilToAnotherClass`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +            throw new ServiceException("Repository read exception", e);
send to constructor `e` from Repository method

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +        if (clazz.getNumber() <= 0) {
class number is between 1 and 11

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +        } else if (clazz.getLetterMark().isEmpty()) {
delete else, simple new `if`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +            throw new ServiceException("Repository create exception", e);
`LOGGER.error(e)`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +        } else if (clazz.getLetterMark().isEmpty()) {
delete `else`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +        } else if (clazz.getLetterMark().isEmpty()) {
new `if`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +            throw new ServiceException("Repository update exception", exc);
always write `exc`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +            List<Clazz> clazzList = clazzIRepository.query(specification, session);
send to `query` method `new ClazzSpecification(...)`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +            List<Clazz> clazzList = clazzIRepository.query(specification, session);
we don't need to save it to variable

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +    public Mark create(Mark obj) throws ServiceException {
change `obj` to `mark`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +    public Mark create(Mark obj) throws ServiceException {
in all places

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +    public Mark create(Mark obj) throws ServiceException {
not only for `mark`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +            obj = markIRepository.create(obj, session);
name such vars `markIRepository` as `markRepository` without `I`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +            Calendar c = new GregorianCalendar();
take out identical checks to methods as in `UserService`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +            throw new ServiceException("Repository update exception", e);
only `exc` in `new ServiceException(..)`

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        if (clazzId <= 0) {
from 1 to 11

2017-03-03 05:46 UTC, mbarouski commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        } else if (obj.getFirstName().isEmpty()) {
not else

2017-03-03 07:24 UTC, zasamen commented on server/src/main/java/school/journal/service/IPupilService.java
> +    Pupil movePupulToAnotherClass(Pupil pupil, Clazz clazz) throws ServiceException;
What should i do?

2017-03-03 07:28 UTC, zasamen commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +            throw new ServiceException("Repository create exception", e);
before throwing new exception?

2017-03-03 12:23 UTC, maximka777 commented on server/src/main/java/school/journal/service/IPupilService.java
> +    Pupil movePupulToAnotherClass(Pupil pupil, Clazz clazz) throws ServiceException;
u -> i

2017-03-03 14:53 UTC, zasamen commented
perhaps done

2017-03-06 09:53 UTC, mbarouski requested changes

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +        return clazzList != null ? clazzList : new LinkedList<Clazz>();
change to ArrayList

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/ClassService.java
> +        if (letterMark.isEmpty())
check for `null` value

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/MarkService.java
> +    private static final Logger LOGGER = Logger.getLogger(ClassService.class);
`Logger.getLogger(MarkService.class)`

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +    private static final Logger LOGGER = Logger.getLogger(ClassService.class);
`PupilService.class`

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +    private static Pattern PHONE_PATTERN = Pattern.compile("\\+375[0-9]+@[0-9a-zA-Z]");
phone number can't consist of letters

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +    private static Pattern PHONE_PATTERN = Pattern.compile("\\+375[0-9]+@[0-9a-zA-Z]");
or explain me

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +    private static Pattern PHONE_PATTERN = Pattern.compile("\\+375[0-9]+@[0-9a-zA-Z]");
use `MobilePhoneValidator` from `utils` package

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        return pupilList != null ? pupilList : new LinkedList<Pupil>();
`ArrayList`

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        validateId(clazz.getClassId());
set fields to default value

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        if (id == null) throw new ServiceException("Invalid id (null)");
if we checks nullable id, may be it can be null

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        if (string.isEmpty()) {
where is check for null value

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +    private void validateStartYear(Date date) throws ServiceException {
explain this method

2017-03-06 09:53 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        if (phone == null) {
use `PhoneValidator` in `utils` package

2017-03-06 09:56 UTC, zasamen commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +    private void validateStartYear(Date date) throws ServiceException {
in code comment or here?

2017-03-06 09:59 UTC, zasamen commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        if (id == null) throw new ServiceException("Invalid id (null)");
ok

2017-03-06 10:00 UTC, zasamen commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        validateId(clazz.getClassId());
explain it here please.

2017-03-06 10:00 UTC, zasamen commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        return pupilList != null ? pupilList : new LinkedList<Pupil>();
Does it matter? But ok.

2017-03-06 10:01 UTC, maximka777 commented on server/src/main/java/school/journal/service/impl/PupilService.java
> +        validateId(clazz.getClassId());
if field have not default value, it will replace old value in db

2017-03-06 17:04 UTC, closed without merging